<?
    $isMy = $USER && !empty($isMe);
    $price = $isMy ? $order['price'] : ($order['price'] - $order['commission']);
?>
<div id="order-<?=$order['id']?>" data-id="<?=$order['id']?>" data-time="<?=$order['executed']?>" class="row col-md-10 col-md-offset-1 order-block<?=$order['state'] != OrderDao::STATE_NEW ? ' disabled' : ''?>"
     onclick="orderist.order.expand('<?=$order['id']?>')">
    <div class="order-price" style="text-align: right;">
        <? if ($isMy): ?>
            <div class="order-get-text" style="margin-bottom: 10px; font-size: 12px; color: gray;"><?=_g('Order price:')?></div>
            <span class="order-price-span label label-info" data-toggle="tooltip" data-placement="left" title="<?=$order['state'] == OrderDao::STATE_NEW ? _g('Executer will get') : _g('Executer got')?>: <?=BaseService::i()->formatMoney($order['price'] - $order['commission'])?> <?=_g('USD')?>"><?=BaseService::i()->formatMoney($price)?> <?=_g('USD')?></span>
        <? else: ?>
            <div class="order-get-text" style="margin-bottom: 10px; font-size: 12px; color: gray;"><?=$USER && $order['executer_id'] == $USER['id'] ? _g('You received') : _g('You will receive')?>:</div>
            <span class="order-price-span label label-warning"><?=BaseService::i()->formatMoney($price)?> <?=_g('USD')?></span>
        <? endif ?>
    </div>

    <div class="order-title">
        <?=$order['title']?>
    </div>

    <div class="order-desc">
        <?=$order['description']?>
    </div>

    <div class="order-footer">
        <div class="order-date">
            <div>
                <?=_g('Client:')?> <a href="/user/profile/?id=<?=$order['user']['id']?>" onclick="event.stopPropagation();"><?=_tr($order['user']['name'])?></a>, <?=BaseService::i()->formatDate($order['inserted'])?>
            <? if (!empty($order['executer'])): ?>
                <br><?=_g('Executer:')?> <a href="/user/profile/?id=<?=$order['executer']['id']?>" onclick="event.stopPropagation();"><?=_tr($order['executer']['name'])?></a>, <?=BaseService::i()->formatDate($order['executed'])?>
            <? endif ?>
            </div>
        </div>
        <div class="order-buttons">
            <? if ($order['state'] == OrderDao::STATE_NEW): ?>
                <span class="loader"></span>
                <? if ($isMy): ?>
                    <button type="button" onclick="orderist.order.deleteConfirm('<?=$order['id']?>'); event.stopPropagation(); return false;" class="btn btn-loading btn-danger order-button">
                        <?=_g('Delete order')?>
                    </button>
                <? else: ?>
                    <button type="button" onclick="orderist.order.execute('<?=$order['id']?>'); event.stopPropagation(); return false;" class="btn btn-loading btn-info order-button">
                        <?=_g('Take order')?>
                    </button>
                <? endif ?>
            <? else: ?>
                <button type="button" onclick="event.stopPropagation(); return false;" class="btn btn-info order-button">
                    <?=$order['state'] == OrderDao::STATE_DELETED ? _g('Order deleted') : _g('Order completed') ?>
                </button>
            <? endif ?>
        </div>
    </div>
</div>
<script>
    orderist.order.init('<?=$order['id']?>');
</script>