<?
    $isMy = $USER && !empty($isMe);
    $price = $isMy ? $order['price'] : ($order['price'] - $order['commission']);
?>
<div id="order-<?=$order['id']?>" data-id="<?=$order['id']?>" data-time="<?=$order['executed']?>" class="row col-md-10 col-md-offset-1 order-block<?=$order['state'] != OrderDao::STATE_NEW ? ' disabled' : ''?>"
     onclick="orderist.order.expand('<?=$order['id']?>')">
    <div class="order-price" style="text-align: right;">
        <? if ($isMy): ?>
            <div class="order-get-text" style="margin-bottom: 10px; font-size: 12px; color: gray;">Стоимость заказа:</div>
            <span class="order-price-span label label-info"><?=BaseService::i()->formatMoney($price)?> р.</span>
        <? else: ?>
            <div class="order-get-text" style="margin-bottom: 10px; font-size: 12px; color: gray;">Вы <?=$USER && $order['executer_id'] == $USER['id'] ? 'получили' : 'получите'?>:</div>
            <span class="order-price-span label label-warning"><?=BaseService::i()->formatMoney($price)?> р.</span>
        <? endif ?>
    </div>

    <div class="order-title">
        <?=$order['title']?>
    </div>

    <div class="order-desc">
        <?=$order['description']?>
    </div>

    <div class="order-footer">
        <div class="order-date">
            <div>
            Заказчик: <a href="/user/profile/?id=<?=$order['user']['id']?>" onclick="event.stopPropagation();"><?=$order['user']['name']?></a>, <?=BaseService::i()->formatDate($order['inserted'])?>
            <? if (!empty($order['executer'])): ?>
                <br>Выполнил: <a href="/user/profile/?id=<?=$order['executer']['id']?>" onclick="event.stopPropagation();"><?=$order['executer']['name']?></a>, <?=BaseService::i()->formatDate($order['executed'])?>
            <? endif ?>
            </div>
        </div>
        <div class="order-buttons">
            <? if ($order['state'] == OrderDao::STATE_NEW): ?>
                <span class="loader"></span>
                <? if ($isMy): ?>
                    <button type="button" onclick="orderist.order.deleteConfirm('<?=$order['id']?>'); event.stopPropagation(); return false;" class="btn btn-loading btn-danger order-button">
                        Удалить заказ
                    </button>
                <? else: ?>
                    <button type="button" onclick="orderist.order.execute('<?=$order['id']?>'); event.stopPropagation(); return false;" class="btn btn-loading btn-info order-button">
                        Выполнить заказ
                    </button>
                <? endif ?>
            <? else: ?>
                <button type="button" onclick="event.stopPropagation(); return false;" class="btn btn-info order-button">
                    <?=$order['state'] == OrderDao::STATE_DELETED ? 'Заказ удалён' : 'Заказ выполнен'?>
                </button>
            <? endif ?>
        </div>
    </div>
</div>
<script>
    orderist.order.init('<?=$order['id']?>');
</script>