<div class="modal-dialog" id="user-signup-popup">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?=_g('Signup on website')?></h4>
        </div>
        <div class="modal-body">
            <form class="form-horizontal" method="post" action="/user/signup/" onsubmit="orderist.user.signup({submit: 1}); return false;">
                <fieldset>
                    <div class="errors-block"></div>
                    <div class="form-group">
                        <span class="help-block input-helper"><?=_g('already_signed_up')?></span>
                        <label for="user_name" class="col-lg-2 control-label"><?=_g('First name')?></label>
                        <div class="col-lg-10">
                            <input type="text" class="form-control" name="user_name" placeholder="<?=_g('How can we address you?')?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="user_email" class="col-lg-2 control-label">Email</label>
                        <div class="col-lg-10">
                            <input type="text" class="form-control" name="user_email" placeholder="<?=_g('We will send email with password here')?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="user_password" class="col-lg-2 control-label"><?=_g('Password')?></label>
                        <div class="col-lg-10">
                            <input type="password" class="form-control" name="user_password" placeholder="<?=_g('If you leave empty then we will generate password for you')?>">
                        </div>
                    </div>
                    <input type="submit" style="display: none;" />
                </fieldset>
            </form>
        </div>
        <div class="modal-footer">
            <span class="loader"></span>
            <button type="button" class="btn btn-default" data-dismiss="modal"><?=_g('Cancel')?></button>
            <button type="button" class="btn btn-loading btn-primary" onclick="$('#user-signup-popup form').submit();"><?=_g('signup_signup')?></button>
        </div>
    </div>
</div>