<div class="modal-dialog" id="order-create-popup">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Разместить новый заказ</h4>
        </div>
        <div class="modal-body">
            <form class="form-horizontal" method="post" action="/order/create/" onsubmit="orderist.order.create(); return false;">
                <fieldset>
                    <div class="errors-block"></div>
                    <div class="form-group">
                        <label for="order_title" class="col-lg-2 control-label">Заголовок</label>
                        <div class="col-lg-10">
                            <input class="form-control" name="order_title" placeholder="Краткое описание заказа" type="text">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="order_description" class="col-lg-2 control-label">Описание</label>
                        <div class="col-lg-10">
                            <textarea class="form-control" rows="3" name="order_description" placeholder="Пожалуйста, развёрнуто опишите, что нужно будет сделать"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="order_price" class="col-lg-2 control-label">Оплата</label>
                        <div class="col-lg-10">
                            <span class="help-block" style="margin-top: 12px;"><span class="jsLink type-order active" onclick="orderist.order.payment.init('order');">заказа</span> / <span class="jsLink type-executer nonactive" onclick="orderist.order.payment.init('executer');">исполнителю</span></span>
                            <div class="input-group">
                                <span class="input-group-addon">Руб.</span>
                                <input type="text" name="order_price" class="form-control" placeholder="0.00">
                            </div>
                            <div class="payment-for-block"></div>
                            <div class="payment-for-order h">
                                <span class="help-block">Это сумма, которую вы заплатите за выполнение заказа.</span>
                                <div>
                                    Комиссия сайта <span class="label label-default order-commission" data-value="<?=$commission?>"><?=$commission * 100?>%</span>,
                                    исполнитель получит <span class="label label-info"><span class="executer-price">0</span> руб.</span>
                                </div>
                            </div>
                            <div class="payment-for-executer h">
                                <span class="help-block">Это сумма, которую получит исполнитель.</span>
                                <div>
                                    Комиссия сайта <span class="label label-default order-commission" data-value="<?=$commission?>"><?=$commission * 100?>%</span>,
                                    вы заплатите <span class="label label-info"><span class="user-price">0</span> руб.</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <input type="submit" style="display: none;" />
                    <input type="text" name="order_payment" class="order_payment" value="" style="display: none;"/>
                    <input type="text" name="order_executer_price" class="order_executer_price" value="0" style="display: none;"/>
                    <input type="text" name="order_user_price" class="order_user_price" value="0" style="display: none;"/>
                </fieldset>
            </form>
        </div>
        <div class="modal-footer create">
            <span class="loader"></span>
            <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
            <button type="button" class="btn btn-loading btn-primary btn-success" onclick="$('#order-create-popup form').submit();">Разместить заказ</button>
        </div>
        <div class="modal-footer done" style="display: none;">
            <div class="alert alert-info">
                Ваш заказ успешно размещен и скоро появится на главной странице.
            </div>
            <a href="/user/orders/">К моим заказам</a>
            <button type="button" class="btn btn-primary btn-success" onclick="orderist.order.createPopup.open();">Новый заказ</button>
            <button type="button" class="btn btn-primary" data-dismiss="modal">Закрыть</button>
        </div>
    </div>
</div>