<div class="modal-dialog" id="order-create-popup">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Разместить новый заказ</h4>
        </div>
        <div class="modal-body">
            <form class="form-horizontal">
                <fieldset>
                    <div class="form-group">
                        <label for="order_title" class="col-lg-2 control-label">Заголовок</label>
                        <div class="col-lg-10">
                            <input class="form-control" name="order_title" placeholder="Краткое описание заказа" type="text">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="order_description" class="col-lg-2 control-label">Описание</label>
                        <div class="col-lg-10">
                            <textarea class="form-control" rows="3" name="order_description"></textarea>
                            <span class="help-block">Примечание: Максимально полно опишите ваш заказ!</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="order_price" class="col-lg-2 control-label">Оплата</label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <span class="input-group-addon">Руб.</span>
                                <input type="text" name="order_price" class="form-control" placeholder="0.00">
                            </div>
                            <span class="help-block">Это сумма, которую вы заплатите за выполнение заказа.</span>
                            <div>
                                Комиссия системы <span class="label label-default order-comission" data-value="<?=$commission?>"><?=$commission * 100?>%</span>,
                                исполнитель получит <span class="label label-info"><span class="executer-price">0</span> руб.</span>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
            <button type="button" class="btn btn-primary" onclick="orderist.order.create();">Разместить заказ</button>
        </div>
    </div>
</div>