<form class="form-horizontal">
    <fieldset>
        <legend><?=_g('Your proifle')?></legend>
        <div class="form-group">
            <label for="user_name" class="col-lg-2 control-label"><?=_g('First name')?></label>
            <div class="col-lg-10">
                <input type="text" class="form-control" name="user_name" placeholder="<?=_tr($USER['name'])?>" disabled>
            </div>
        </div>
        <div class="form-group">
            <label for="user_email" class="col-lg-2 control-label">Email</label>
            <div class="col-lg-10">
                <input type="text" class="form-control" name="user_email" placeholder="<?=$USER['email']?>" disabled>
            </div>
        </div>
    </fieldset>
</form>