<ul class="nav nav-tabs">
    <li role="presentation" class="<?=$state === OrderDao::STATE_NEW ? 'active' : ''?>"><a href="/user/orders/?state=<?=OrderDao::STATE_NEW?>"><?=_g('Active')?></a></li>
    <li role="presentation" class="<?=$state === OrderDao::STATE_EXECUTED ? 'active' : ''?>"><a href="/user/orders/?state=<?=OrderDao::STATE_EXECUTED?>"><?=_g('Completed')?></a></li>
    <li role="presentation" style="margin-left: 20px;" class="<?=$state === OrderDao::FAKE_STATE_EXECUTER ? 'active' : ''?>">
        <a href="/user/orders/?state=<?=OrderDao::FAKE_STATE_EXECUTER?>"><?=_g('Executed by me')?></a>
    </li>
</ul>

<div id="orders-block">
    <div class="list">
        <? if (empty($orders)): ?>
            <? if (!$state || $state === OrderDao::STATE_NEW || $state === OrderDao::STATE_EXECUTED): ?>
                <?
                    $stateText = !$state ? '' : ($state === OrderDao::STATE_NEW ? (' ' . _g('active')) : (' ' . _g('completed')));
                ?>
                <h4>
                    <?=_f('orders_no_orders', $stateText)?>
                </h4>
            <? else: ?>
                <h4>
                    <?=_g('orders_no_completed')?>
                </h4>
            <? endif ?>
        <? endif ?>
        <? include '../apps/views/order/blocks/orders.phtml' ?>
    </div>
    <div class="row col-md-10 col-md-offset-1 loader-block">
        <img src="<?=BaseTag::path('/img/loader.gif')?>" class="loader-img" />
    </div>
</div>

<script>
    orderist.order.loadMoreUrl = '/user/orders/?state=<?=$state?>';
    orderist.order.offset = '<?=$nextOffset?>'
    orderist.order.isFinished = <?=empty($hasNext) ? 'true' : 'false'?>;
</script>

<? if (!empty($hasNext)): ?>
    <script>
        $(window).scroll(function() {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 300) {
                orderist.order.loadMore();
            }
        });

        $(document).ready(function() {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 300) {
                orderist.order.loadMore();
            }
        });
    </script>
<? endif ?>
