<script>
    orderist.order.loadMoreUrl = '/user/getorderspage/?state=<?=$state?>';
</script>
<ul class="nav nav-tabs">
    <li role="presentation" class="<?=$state === OrderDao::STATE_NEW ? 'active' : ''?>"><a href="/user/orders/?state=<?=OrderDao::STATE_NEW?>">Активные</a></li>
    <li role="presentation" class="<?=$state === OrderDao::STATE_EXECUTED ? 'active' : ''?>"><a href="/user/orders/?state=<?=OrderDao::STATE_EXECUTED?>">Выполненные</a></li>
    <li role="presentation" class="<?=!$state ? 'active' : ''?>"><a href="/user/orders/?state=0">Все закакзы</a></li>
</ul>

<div id="orders-block">
    <? if (empty($orders)): ?>
        <?
        $stateText = !$state ? '' : ($state === OrderDao::STATE_NEW ? ' активных' : ' выполненных');
        ?>
        <h4>
            У вас нет<?=$stateText?> заказов. Вы можете <a href="/order/create/" onclick="orderist.order.createPopup(); return false;">разместить новый заказ</a>.
        </h4>
    <? endif ?>

    <? include '../apps/views/index/orders_block.phtml' ?>
</div>

<? if (!empty($hasNext)): ?>
    <script>
        $(window).scroll(function() {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 300) {
                orderist.order.loadMore();
            }
        });

        $(document).ready(function() {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 300) {
                orderist.order.loadMore();
            }
        });
    </script>
<? endif ?>
