<div class="modal-dialog" id="user-signup-popup">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Регистрация на сайте</h4>
        </div>
        <div class="modal-body">
            <form class="form-horizontal" method="post" action="/user/signup/" onsubmit="orderist.user.signup(true); return false;">
                <fieldset>
                    <div class="errors-block"></div>
                    <div class="form-group">
                        <label for="user_name" class="col-lg-2 control-label">Ваше имя</label>
                        <div class="col-lg-10">
                            <input type="text" class="form-control" name="user_name" placeholder="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="user_email" class="col-lg-2 control-label">Email</label>
                        <div class="col-lg-10">
                            <input type="text" class="form-control" name="user_email" placeholder="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="user_password" class="col-lg-2 control-label">Пароль</label>
                        <div class="col-lg-10">
                            <input type="password" class="form-control" name="user_password" placeholder="">
                        </div>
                    </div>
                    <input type="submit" style="display: none;" />
                </fieldset>
            </form>
        </div>
        <div class="modal-footer">
            <span class="loader"></span>
            <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
            <button type="button" class="btn btn-loading btn-primary" onclick="$('#user-signup-popup form').submit();">Зарегистрироваться</button>
        </div>
    </div>
</div>