<div id="orders-block">
    <? include 'orders_block.phtml' ?>
</div>

<script>
    $(window).scroll(function() {
        if ($(window).scrollTop() + $(window).height() >= $(document).height() - 300) {
            orderist.order.loadMore();
        }
    });

    $(document).ready(function() {
        if ($(window).scrollTop() + $(window).height() >= $(document).height() - 300) {
            orderist.order.loadMore();
        }
    });
</script>