<div id="orders-block">
    <div class="list">
        <? include '../apps/views/order/blocks/orders.phtml' ?>
    </div>
    <div class="row col-md-10 col-md-offset-1 loader-block">
        <img src="<?=BaseTag::path('/img/loader.gif')?>" class="loader-img" />
    </div>
</div>

<script>
    orderist.order.loadMoreUrl = '/index/orders/';
    orderist.order.offset = '<?=$nextOffset?>';
    orderist.order.isFinished = <?=empty($hasNext) ? 'true' : 'false'?>;
</script>

<? if (!empty($hasNext)): ?>
    <script>
        $(window).scroll(function() {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 300) {
                orderist.order.loadMore();
            }
        });

        $(document).ready(function() {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 300) {
                orderist.order.loadMore();
            }
        });
    </script>
<? endif ?>