<?
    $isMy = $USER && !empty($isMe);
    $price = $isMy ? $order['price'] / 100 : (($order['price'] - $order['commission']) / 100);
?>
<div id="order-<?=$order['id']?>" data-id="<?=$order['id']?>" class="row col-md-10 col-md-offset-1 order-block<?=$order['state'] != OrderDao::STATE_NEW ? ' disabled' : ''?>"
     onclick="orderist.order.expand('<?=$order['id']?>')">
    <div class="order-price" style="text-align: right;">
        <? if ($isMy): ?>
            <div class="order-get-text" style="margin-bottom: 10px; font-size: 12px; color: gray;">Стоимость заказа:</div>
            <span class="label label-info"><?=number_format($price, 2, ',', ' ')?> р.</span>
        <? else: ?>
            <div class="order-get-text" style="margin-bottom: 10px; font-size: 12px; color: gray;">Вы <?=$USER && $order['executer_id'] == $USER['id'] ? 'получили' : 'получите'?>:</div>
            <span class="label label-warning"><?=number_format($price, 2, ',', ' ')?> р.</span>
        <? endif ?>
    </div>

    <div class="order-title">
        <?=$order['title']?>
    </div>

    <div class="order-desc">
        <?=$order['description']?>
    </div>

    <div class="order-footer">
        <div class="order-date">
            От: <?=$order['user']['name']?>, создан: <?=date('Y-m-d H:i:s', $order['inserted'])?>
        </div>
        <div class="order-buttons">
            <? if ($order['state'] == OrderDao::STATE_NEW): ?>
                <span class="loader"></span>
                <? if ($isMy): ?>
                    <button type="button" onclick="orderist.order.deleteConfirm('<?=$order['id']?>'); event.stopPropagation(); return false;" class="btn btn-loading btn-danger order-button">
                        Удалить заказ
                    </button>
                <? else: ?>
                    <button type="button" onclick="orderist.order.execute('<?=$order['id']?>'); event.stopPropagation(); return false;" class="btn btn-loading btn-info order-button">
                        Выполнить заказ
                    </button>
                <? endif ?>
            <? else: ?>
                <button type="button" onclick="event.stopPropagation(); return false;" class="btn btn-info order-button">
                    Заказ выполнен
                </button>
            <? endif ?>
        </div>
    </div>
</div>
<script>
    orderist.order.init('<?=$order['id']?>');
</script>