<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
    <title>Заказист</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link rel="shortcut icon" href="<?=BaseTag::path('/favicon.ico')?>">
    <link rel="stylesheet" href="<?=BaseTag::path('/lib/bootstrap.min.css')?>" media="screen">
    <link rel="stylesheet" href="<?=BaseTag::path('/base.css')?>" media="screen">
    <link rel="stylesheet" href="<?=BaseTag::path('/lib/spinner.css')?>" media="screen">

    <noscript><meta http-equiv="refresh" content="0; URL=https://vk.com/badbrowser.php"></noscript>
    <script src="<?=BaseTag::path('/lib/jquery-1.12.2.min.js')?>"></script>
    <script src="https://cdn.socket.io/socket.io-1.4.5.js"></script>
    <script src="<?=BaseTag::path('/lib/bootstrap.min.js')?>"></script>
    <script src="<?=BaseTag::path('/lib/bootstrap.fix.js')?>"></script>
    <script src="<?=BaseTag::path('/base.js')?>"></script>
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a href="/" class="navbar-brand">Заказист</a>
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
            <ul class="nav navbar-nav">
                <li class="<?=$navTab == BaseController::TAB_ORDERS ? 'active' : 'unactive'?>">
                    <a href="/orders/">Все заказы</a>
                </li>
                <? if ($USER): ?>
                    <li class="<?=$navTab == BaseController::TAB_MY_ORDERS ? 'active' : 'unactive'?>">
                        <a href="/user/orders/">Мои заказы</a>
                    </li>
                <? endif ?>
                <li>
                    <form class="navbar-form">
                        <a href="/order/create/" onclick="orderist.order.createPopup(); return false;" class="btn btn-success btn-sm">+ Разместить заказ</a>
                    </form>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <? if ($USER): ?>
                    <li class="<?=$navTab == BaseController::TAB_CASH ? 'active' : 'unactive'?>">
                        <a href="/user/cash/">Баланс: <span style="font-weight: bold;"><span class="user-cash"><?=UserDao::i()->getField($USER, 'cash')?></span> руб.</span></a>
                    </li>
                    <li class="dropdown <?=$navTab == BaseController::TAB_USER ? 'active' : 'unactive'?>">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="/user/"><?=$USER['name']?> <span class="caret"></span></a>
                        <ul class="dropdown-menu" aria-labelledby="download">
                            <li><a href="/user/cash/">Баланс</a></li>
                            <li><a href="/user/">Профиль</a></li>
                            <li class="divider"></li>
                            <li><a href="/user/logout/">Выход</a></li>
                        </ul>
                    </li>
                <? else: ?>
                    <li>
                        <a href="/user/login/" onclick="orderist.user.login(); return false;">Вход</a>
                    </li>
                    <li>
                        <a href="/user/signup/" onclick="orderist.user.signup(); return false;">Регистрация</a>
                    </li>
                <? endif ?>
            </ul>
        </div>
    </div>
</div>

<div class="container">
    <?=$this->getContent()?>
</div>

<div id="modal-popup" class="modal fade" role="dialog"></div>

<? if (!empty($requestParams['create'])): ?>
    <script>
        $(document).ready(function() {
            orderist.order.createPopup();
        });
    </script>
<? endif ?>

</body>
</html>