<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
    <title><?=_g('Orderist')?></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link rel="shortcut icon" href="<?=BaseTag::path('/img/favicon.ico')?>">
    <link rel="stylesheet" href="<?=BaseTag::path('/lib/bootstrap.min.css')?>" media="screen">
    <link rel="stylesheet" href="<?=BaseTag::path('/base.css')?>" media="screen">

    <noscript><meta http-equiv="refresh" content="0; URL=https://vk.com/badbrowser.php"></noscript>
    <script src="<?=BaseTag::path('/lib/jquery-1.12.2.min.js')?>"></script>
    <script src="<?=BaseTag::path('/lib/socket.io-1.4.5.js')?>"></script>
    <script src="<?=BaseTag::path('/lib/bootstrap.min.js')?>"></script>
    <script src="<?=BaseTag::path('/lib/bootstrap.fix.js')?>"></script>
    <script src="<?=BaseTag::path('/base.js')?>"></script>
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a href="/" class="navbar-brand">
                <img src="<?=BaseTag::path('/img/logo.gif')?>" />
            </a>
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
            <ul class="nav navbar-nav">
                <li class="all-orders <?=$navTab == BaseController::TAB_ORDERS ? 'active' : 'unactive'?>">
                    <a href="/orders/"><?=_g('All orders')?></a>
                </li>
                <? if ($USER): ?>
                    <li class="<?=$navTab == BaseController::TAB_MY_ORDERS ? 'active' : 'unactive'?>">
                        <a href="/user/orders/"><?=_g('My orders')?></a>
                    </li>
                <? endif ?>
                <li>
                    <form class="navbar-form">
                        <a href="/order/create/" onclick="orderist.order.createPopup.open(); return false;" class="btn btn-success btn-sm">+ <?=_g('Create order')?></a>
                    </form>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <? if ($USER): ?>
                    <li class="<?=$navTab == BaseController::TAB_CASH ? 'active' : 'unactive'?>">
                        <a href="/user/cash/" style="max-height: 51px; white-space: nowrap; max-width: 200px; overflow: hidden;"><?=_g('Balance')?>: <span style="font-weight: bold;"><span class="user-cash"><?=UserDao::i()->getField($USER, 'cash')?></span> <?=_g('USD')?></span></a>
                    </li>
                    <li class="dropdown <?=$navTab == BaseController::TAB_USER ? 'active' : 'unactive'?>">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="/user/"><?=mb_strlen($USER['name']) <= 10 ? _tr($USER['name']) : _g('Profile')?> <span class="caret"></span></a>
                        <ul class="dropdown-menu" aria-labelledby="download">
                            <li><a href="/user/cash/"><?=_g('Balance')?></a></li>
                            <li><a href="/user/"><?=_g('Profile')?></a></li>
                            <li class="divider"></li>
                            <li><a href="/user/logout/"><?=_g('Log out')?></a></li>
                        </ul>
                    </li>
                <? else: ?>
                    <li>
                        <a href="/user/login/" onclick="orderist.user.login(); return false;"><?=_g('My profile')?></a>
                    </li>
                    <li>
                        <a href="/user/signup/" onclick="orderist.user.signup(); return false;"><?=_g('Signup')?></a>
                    </li>
                <? endif ?>
            </ul>
        </div>
    </div>
</div>

<div class="container">
    <?=$this->getContent()?>
</div>

<div id="modal-popup" class="modal fade" role="dialog"></div>

<div style="display: none;">
    <img src="<?=BaseTag::path('/img/loader.gif')?>" class="loader-img" />
</div>

<? if (!empty($requestParams['create'])): ?>
    <script>
        $(document).ready(function() {
            orderist.order.createPopup.open();
        });
    </script>
<? endif ?>

</body>
</html>