<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
    <title>Заказист</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link rel="stylesheet" href="<?=BaseTag::path('/bootstrap.min.css')?>" media="screen">
    <link rel="stylesheet" href="<?=BaseTag::path('/base.css')?>" media="screen">

    <script src="<?=BaseTag::path('/jquery-1.12.2.min.js')?>"></script>
    <script src="<?=BaseTag::path('/bootstrap.min.js')?>"></script>
    <script src="<?=BaseTag::path('/base.js')?>"></script>
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a href="/" class="navbar-brand">Заказист</a>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
            <ul class="nav navbar-nav">
                <li class="<?=$navTab == BaseController::TAB_ORDERS ? 'active' : 'unactive'?>">
                    <a href="/orders/">Все заказы</a>
                </li>
                <li class="<?=$navTab == BaseController::TAB_MY_ORDERS ? 'active' : 'unactive'?>">
                    <a href="/user/orders/">Мои заказы</a>
                </li>
                <li>
                    <form class="navbar-form">
                        <a href="/order/create/" onclick="orderist.order.createPopup(); return false;" class="btn btn-success btn-sm">+ Разместить заказ</a>
                    </form>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <? if ($USER): ?>
                    <li class="<?=$navTab == BaseController::TAB_CASH ? 'active' : 'unactive'?>">
                        <a href="/user/cash/">Баланс: <span style="font-weight: bold;"><span id="cash"><?=UserDao::i()->getField($USER, 'cash')?></span> руб.</span></a>
                    </li>
                    <li class="dropdown <?=$navTab == BaseController::TAB_USER ? 'active' : 'unactive'?>">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><?=$USER['name']?> <span class="caret"></span></a>
                        <ul class="dropdown-menu" aria-labelledby="download">
                            <li><a href="/user/cash/">Баланс</a></li>
                            <li><a href="/user/">Профиль</a></li>
                            <li class="divider"></li>
                            <li><a href="/user/logout/">Выход</a></li>
                        </ul>
                    </li>
                <? else: ?>
                    <li>
                        <a href="/user/login/" onclick="orderist.user.login(); return false;">Вход</a>
                    </li>
                    <li>
                        <a href="/user/signup/" onclick="orderist.user.signup(); return false;">Регистрация</a>
                    </li>
                <? endif ?>
            </ul>
        </div>
    </div>
</div>

<div class="container">
    <?=$this->getContent()?>
</div>

<div id="modal-popup" class="modal fade" role="dialog"></div>
<div id="modal-alert" style="display: none;">
    <div class="modal-dialog" id="order-create-popup">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Произошла ошибка</h4>
            </div>
            <div class="modal-body"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Закрыть</button>
                </div>
        </div>
    </div>
</div>

</body>
</html>