<? if ($text): ?>
    <div class="alert alert-info"><?=$text?></div>
<? endif ?>

<p>
    <?=_g('Our revenue:')?> <span class="label label-info"><?=BaseService::i()->formatMoney($income['commission'])?> <?=_g('USD')?></span><br>
</p>

<? if (BaseService::i()->getCookie('debug')): ?>
    <a href="/admin/debug/?debug=0">Disable debug</a><br>
<? else :?>
    <a href="/admin/debug/?debug=1">Enable debug</a><br>
<? endif ?>

<br/>

<a href="/admin/clearmemcache/">Clear Memcache</a><br>
<a href="/admin/recover/"><?=_g('Check data consistency')?></a><br>

<br/>

<a target="_blank" href="/adminer.php">MySQL Admin</a> (Login/Password: readonly)<br>