<? foreach ($payments as $payment): ?>
    <tr class="user-payment-block <?=$payment['amount'] < 0 ? 'negative': 'positive'?>" data-id="<?=$payment['id']?>">
        <td><?=date('Y-m-d H:i:s', $payment['inserted'])?></td>
        <td><?=BaseService::i()->formatMoney($payment['amount'])?> <?=_g('USD')?></td>
        <td>
            <? if (!empty($payment['order_id'])): ?>
                <?=$payment['amount'] < 0 ? _g('Withdrawal for order') : _g('Payment for order')?> #<a href="/order/order/?id=<?=$payment['order_id']?>"><?=$payment['order_id']?></a>
            <? else: ?>
                <?=$payment['amount'] < 0 ? _g('Withdrawal') : _g('Payment')?>
            <? endif ?>
        </td>
    </tr>
<? endforeach ?>